chore(deps): update dependency eslint-config-next to ^13.5.6 (#2105)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[eslint-config-next](https://nextjs.org/docs/app/building-your-application/configuring/eslint#eslint-config)
([source](https://togithub.com/vercel/next.js)) | [`^13.4.19` ->
`^13.5.6`](https://renovatebot.com/diffs/npm/eslint-config-next/13.4.19/13.5.6)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/eslint-config-next/13.5.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/eslint-config-next/13.5.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/eslint-config-next/13.4.19/13.5.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint-config-next/13.4.19/13.5.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>vercel/next.js (eslint-config-next)</summary>

###
[`v13.5.6`](https://togithub.com/vercel/next.js/releases/tag/v13.5.6)

[Compare
Source](https://togithub.com/vercel/next.js/compare/v13.5.5...v13.5.6)

##### Core Changes

- Upgrade edge-runtime/cookies
[#&#8203;57021](https://togithub.com/vercel/next.js/issues/57021)
- Patch React with fix for write-after-close for ReadableStream
[#&#8203;57011](https://togithub.com/vercel/next.js/issues/57011)

##### Credits

Huge thanks to [@&#8203;ijjk](https://togithub.com/ijjk)
[@&#8203;huozhi](https://togithub.com/huozhi)
[@&#8203;gnoff](https://togithub.com/gnoff) for helping!

###
[`v13.5.5`](https://togithub.com/vercel/next.js/compare/v13.5.4...v13.5.5)

[Compare
Source](https://togithub.com/vercel/next.js/compare/v13.5.4...v13.5.5)

###
[`v13.5.4`](https://togithub.com/vercel/next.js/releases/tag/v13.5.4)

[Compare
Source](https://togithub.com/vercel/next.js/compare/v13.5.3...v13.5.4)

##### Core Changes

- chore: NextJS -> Next.js:
[#&#8203;55961](https://togithub.com/vercel/next.js/issues/55961)
- fix-failed-to-generate-self-signed-certificate
issue:[#&#8203;55891](https://togithub.com/vercel/next.js/issues/55891):
[#&#8203;55947](https://togithub.com/vercel/next.js/issues/55947)
- Remove .test.js from dist:
[#&#8203;55946](https://togithub.com/vercel/next.js/issues/55946)
- Turbopack next/font/google: don't insert css rules for multiple
weights or styles:
[#&#8203;55852](https://togithub.com/vercel/next.js/issues/55852)
- Fix stale revalidate stream handling:
[#&#8203;55978](https://togithub.com/vercel/next.js/issues/55978)
- turbopack: improve turbopack/test stability:
[#&#8203;56024](https://togithub.com/vercel/next.js/issues/56024)
- Mark testmode fetches internal:
[#&#8203;56036](https://togithub.com/vercel/next.js/issues/56036)
- chore: Remove 'beta.' Subdomain from `beta.nextjs.org` Links:
[#&#8203;55924](https://togithub.com/vercel/next.js/issues/55924)
- Remove experimental.sharedPool:
[#&#8203;56021](https://togithub.com/vercel/next.js/issues/56021)
- fix(worker): pass env to build worker w/
`config.experimental.workerThreads`:
[#&#8203;55257](https://togithub.com/vercel/next.js/issues/55257)
- Update `swc_core` to `v0.83.26`:
[#&#8203;55780](https://togithub.com/vercel/next.js/issues/55780)
- Revert "Update `swc_core` to `v0.83.26`":
[#&#8203;56077](https://togithub.com/vercel/next.js/issues/56077)
- fix reporting of illegal segments when directory only contains
irrelevant files:
[#&#8203;56076](https://togithub.com/vercel/next.js/issues/56076)
- Make `permanentRedirect` return 308 in route handlers:
[#&#8203;56065](https://togithub.com/vercel/next.js/issues/56065)
- Remove unneeded next-dev js in next-core:
[#&#8203;56039](https://togithub.com/vercel/next.js/issues/56039)
- Fix: Use `boolean` instead of `false` for experimental logging config:
[#&#8203;56110](https://togithub.com/vercel/next.js/issues/56110)
- chore: remove chalk in favor of picocolors:
[#&#8203;55992](https://togithub.com/vercel/next.js/issues/55992)
- Revert: "Generate prefetch RSC payload during build for SSR paths
([#&#8203;54403](https://togithub.com/vercel/next.js/issues/54403))":
[#&#8203;56059](https://togithub.com/vercel/next.js/issues/56059)
- fetching logging on edge:
[#&#8203;56108](https://togithub.com/vercel/next.js/issues/56108)
- Optimize build trace handling:
[#&#8203;56048](https://togithub.com/vercel/next.js/issues/56048)
- Update font data:
[#&#8203;56121](https://togithub.com/vercel/next.js/issues/56121)
- feat(turbopack): port bloom filter to nexturbo:
[#&#8203;55678](https://togithub.com/vercel/next.js/issues/55678)
- Fixes performance problems due to TaskScopes:
[#&#8203;55721](https://togithub.com/vercel/next.js/issues/55721)
- perf: remove react dom legacy from app router:
[#&#8203;56082](https://togithub.com/vercel/next.js/issues/56082)
- perf: replace zod with superstruct:
[#&#8203;56083](https://togithub.com/vercel/next.js/issues/56083)
- perf: externalise ws for bundled server:
[#&#8203;56095](https://togithub.com/vercel/next.js/issues/56095)
- misc: refactor node utils:
[#&#8203;56096](https://togithub.com/vercel/next.js/issues/56096)
- Add support for skipTrailingSlashRedirect and
skipMiddlewareUrlNormalize in Turbopack:
[#&#8203;56147](https://togithub.com/vercel/next.js/issues/56147)
- Add experimental.scrollRestoration for Turbopack:
[#&#8203;56150](https://togithub.com/vercel/next.js/issues/56150)
- misc: refactor handleExternals:
[#&#8203;56161](https://togithub.com/vercel/next.js/issues/56161)
- perf: add option to bundle pages externals:
[#&#8203;56162](https://togithub.com/vercel/next.js/issues/56162)
- Allow jest to run with use server directive:
[#&#8203;56148](https://togithub.com/vercel/next.js/issues/56148)
- Update experimental compile cache handling:
[#&#8203;56139](https://togithub.com/vercel/next.js/issues/56139)
- App render related code clean up:
[#&#8203;56178](https://togithub.com/vercel/next.js/issues/56178)
- Add support for i18n config in Turbopack:
[#&#8203;56182](https://togithub.com/vercel/next.js/issues/56182)
- Implement list of config options for Turbopack:
[#&#8203;56188](https://togithub.com/vercel/next.js/issues/56188)
- Turbopack: add support for an assetPrefix and basePath:
[#&#8203;56058](https://togithub.com/vercel/next.js/issues/56058)
- update turbopack:
[#&#8203;56197](https://togithub.com/vercel/next.js/issues/56197)
- Update supported options list to reflect
[#&#8203;56188](https://togithub.com/vercel/next.js/issues/56188):
[#&#8203;56200](https://togithub.com/vercel/next.js/issues/56200)
- Add support for experimental.logging.level in Turbopack:
[#&#8203;56201](https://togithub.com/vercel/next.js/issues/56201)
- Add next.config.js options to turbopack warning file:
[#&#8203;56207](https://togithub.com/vercel/next.js/issues/56207)
- fix: [@&#8203;libsql/client](https://togithub.com/libsql/client) build
error: [#&#8203;56192](https://togithub.com/vercel/next.js/issues/56192)
- chore: bump `postcss`:
[#&#8203;56225](https://togithub.com/vercel/next.js/issues/56225)
- Add additional handling for experimental-compile:
[#&#8203;56224](https://togithub.com/vercel/next.js/issues/56224)
- Drop ipc server headers filters:
[#&#8203;56226](https://togithub.com/vercel/next.js/issues/56226)
- only override NODE_EXTRA_CA_CERTS when using experimental https flag:
[#&#8203;56252](https://togithub.com/vercel/next.js/issues/56252)
- Pass same mangling option as terser to SWC minifier:
[#&#8203;56281](https://togithub.com/vercel/next.js/issues/56281)
- update turbopack:
[#&#8203;56285](https://togithub.com/vercel/next.js/issues/56285)
- clear require cache only when needed:
[#&#8203;56198](https://togithub.com/vercel/next.js/issues/56198)
- misc: enable source maps for bundled runtime:
[#&#8203;56289](https://togithub.com/vercel/next.js/issues/56289)
- misc: shortcut styled-jsx in external resolution:
[#&#8203;56291](https://togithub.com/vercel/next.js/issues/56291)
- Support serverRuntimeConfig and publicRuntimeConfig in Turbopack:
[#&#8203;56310](https://togithub.com/vercel/next.js/issues/56310)
- Reland static prefetches & fix prefetch bailout behavior:
[#&#8203;56228](https://togithub.com/vercel/next.js/issues/56228)
-
fix([#&#8203;53190](https://togithub.com/vercel/next.js/issues/53190)):
add missing crossOrigin to assetsPrefix resources:
[#&#8203;56311](https://togithub.com/vercel/next.js/issues/56311)
- misc: fix instrumentation with bundled server:
[#&#8203;56318](https://togithub.com/vercel/next.js/issues/56318)
- fix(next/client): keep hash when navigating from app to pages router:
[#&#8203;56223](https://togithub.com/vercel/next.js/issues/56223)
- fix: support both decoded and encoded url requests of conventioned
files :
[#&#8203;56187](https://togithub.com/vercel/next.js/issues/56187)
- fix: Invalid URL (404) provided on server actions error:
[#&#8203;56323](https://togithub.com/vercel/next.js/issues/56323)
- Revert "misc: shortcut styled-jsx in external resolution
([#&#8203;56291](https://togithub.com/vercel/next.js/issues/56291))":
[#&#8203;56334](https://togithub.com/vercel/next.js/issues/56334)
- Fix build output logging order:
[#&#8203;56335](https://togithub.com/vercel/next.js/issues/56335)

##### Documentation Changes

- docs: add `not-found` to file conventions page:
[#&#8203;55944](https://togithub.com/vercel/next.js/issues/55944)
- Update 03-linking-and-navigating.mdx:
[#&#8203;55907](https://togithub.com/vercel/next.js/issues/55907)
- docs: Correct place for passing `extension` option to `createMDX()`:
[#&#8203;55967](https://togithub.com/vercel/next.js/issues/55967)
- docs-55629 update router cache column in cache interactions api table:
[#&#8203;55630](https://togithub.com/vercel/next.js/issues/55630)
- Update 03-linking-and-navigating.mdx:
[#&#8203;55969](https://togithub.com/vercel/next.js/issues/55969)
- Updates "Prerender Error" page for App Router:
[#&#8203;56044](https://togithub.com/vercel/next.js/issues/56044)
- Add the default import alias to create-next-app prompt for clarity:
[#&#8203;55896](https://togithub.com/vercel/next.js/issues/55896)
- Update revalidatePath.mdx to fix confusing wording of arguments
section.:
[#&#8203;56099](https://togithub.com/vercel/next.js/issues/56099)
- docs: Renamed function that is used by other name:
[#&#8203;56170](https://togithub.com/vercel/next.js/issues/56170)
- (docs) Document Server Actions `.bind` method:
[#&#8203;56164](https://togithub.com/vercel/next.js/issues/56164)
- docs: Use `Response.json` over `NextResponse.json`:
[#&#8203;56173](https://togithub.com/vercel/next.js/issues/56173)
- correcting link to useSearchParams ref:
[#&#8203;56169](https://togithub.com/vercel/next.js/issues/56169)
- docs(sharp-missing-in-production.mdx): update standalone command:
[#&#8203;56191](https://togithub.com/vercel/next.js/issues/56191)
- docs(sharp-missing-in-production.mdx): update standalone command:
[#&#8203;56239](https://togithub.com/vercel/next.js/issues/56239)
- Update image.mdx:
[#&#8203;56269](https://togithub.com/vercel/next.js/issues/56269)
- Update image.mdx:
[#&#8203;56266](https://togithub.com/vercel/next.js/issues/56266)

##### Example Changes

- chore(examples): bump dependency versions:
[#&#8203;55899](https://togithub.com/vercel/next.js/issues/55899)
- Update to with-supertokens example app:
[#&#8203;56035](https://togithub.com/vercel/next.js/issues/56035)
- Update dependencies in examples :
[#&#8203;55993](https://togithub.com/vercel/next.js/issues/55993)
- Chore/update with supabase demo deploy button:
[#&#8203;52483](https://togithub.com/vercel/next.js/issues/52483)
- chore(examples): remove deprecated dependency from `with-jest`:
[#&#8203;56152](https://togithub.com/vercel/next.js/issues/56152)
- chore(examples): fix `with-jest` types:
[#&#8203;56193](https://togithub.com/vercel/next.js/issues/56193)
- (Examples) update Grafbase example:
[#&#8203;54705](https://togithub.com/vercel/next.js/issues/54705)
- fix: typo in `with-stripe-typescript` example:
[#&#8203;56274](https://togithub.com/vercel/next.js/issues/56274)

##### Misc Changes

- Skip production tests for Turbopack:
[#&#8203;56045](https://togithub.com/vercel/next.js/issues/56045)
- Fix invalid build-and-test workflow:
[#&#8203;56053](https://togithub.com/vercel/next.js/issues/56053)
- turbopack: Add more skipped tests:
[#&#8203;56052](https://togithub.com/vercel/next.js/issues/56052)
- Skip next build test:
[#&#8203;56079](https://togithub.com/vercel/next.js/issues/56079)
- add flakey test:
[#&#8203;56080](https://togithub.com/vercel/next.js/issues/56080)
- Skip more production tests for turbopack:
[#&#8203;56084](https://togithub.com/vercel/next.js/issues/56084)
- Ensure tests suites have unique names:
[#&#8203;56085](https://togithub.com/vercel/next.js/issues/56085)
- Skip experimental.nextScriptWorkers test for Turbopack:
[#&#8203;56086](https://togithub.com/vercel/next.js/issues/56086)
- Skip production tests for Turbopack:
[#&#8203;56089](https://togithub.com/vercel/next.js/issues/56089)
- Skip Babel tests for Turbopack:
[#&#8203;56091](https://togithub.com/vercel/next.js/issues/56091)
- misc: add node-version file:
[#&#8203;55938](https://togithub.com/vercel/next.js/issues/55938)
- Ensure unique name for app dir css tests:
[#&#8203;56088](https://togithub.com/vercel/next.js/issues/56088)
- Decrease default test timeouts:
[#&#8203;56116](https://togithub.com/vercel/next.js/issues/56116)
- misc: stop hiding node_modules in vscode:
[#&#8203;56081](https://togithub.com/vercel/next.js/issues/56081)
- special case timeout on windows:
[#&#8203;56120](https://togithub.com/vercel/next.js/issues/56120)
- Turbopack: update test manifest:
[#&#8203;56133](https://togithub.com/vercel/next.js/issues/56133)
- More test updates:
[#&#8203;56146](https://togithub.com/vercel/next.js/issues/56146)
- fix(cna): pin dependency versions:
[#&#8203;56177](https://togithub.com/vercel/next.js/issues/56177)
- Update `swc_core` to `v0.83.28`:
[#&#8203;56134](https://togithub.com/vercel/next.js/issues/56134)
- Fix middleware-general test for Turbopack:
[#&#8203;56211](https://togithub.com/vercel/next.js/issues/56211)
- More Turbopack test fixes:
[#&#8203;56248](https://togithub.com/vercel/next.js/issues/56248)
- update test mainfest:
[#&#8203;56214](https://togithub.com/vercel/next.js/issues/56214)
- More Turbopack fixes:
[#&#8203;56275](https://togithub.com/vercel/next.js/issues/56275)
- More Turbopack fixes:
[#&#8203;56299](https://togithub.com/vercel/next.js/issues/56299)
- misc: update code owners:
[#&#8203;56290](https://togithub.com/vercel/next.js/issues/56290)
- Fix flaky test for size output:
[#&#8203;56303](https://togithub.com/vercel/next.js/issues/56303)
- update webp crate:
[#&#8203;56307](https://togithub.com/vercel/next.js/issues/56307)
- Remove buildId test as it's no longer relevant:
[#&#8203;56316](https://togithub.com/vercel/next.js/issues/56316)
- Add code freeze GitHub actions for releasing:
[#&#8203;56325](https://togithub.com/vercel/next.js/issues/56325)
- test: add flaky turbopack integration tests to manifest:
[#&#8203;56309](https://togithub.com/vercel/next.js/issues/56309)

##### Credits

Huge thanks to
[@&#8203;balazsorban44](https://togithub.com/balazsorban44),
[@&#8203;sdkdeepa](https://togithub.com/sdkdeepa),
[@&#8203;aayman997](https://togithub.com/aayman997),
[@&#8203;mayank1513](https://togithub.com/mayank1513),
[@&#8203;timneutkens](https://togithub.com/timneutkens),
[@&#8203;2XG-DEV](https://togithub.com/2XG-DEV),
[@&#8203;eliot-akira](https://togithub.com/eliot-akira),
[@&#8203;hi-matthew](https://togithub.com/hi-matthew),
[@&#8203;riobits](https://togithub.com/riobits),
[@&#8203;wbinnssmith](https://togithub.com/wbinnssmith),
[@&#8203;ijjk](https://togithub.com/ijjk),
[@&#8203;sokra](https://togithub.com/sokra),
[@&#8203;dvoytenko](https://togithub.com/dvoytenko),
[@&#8203;rishabhpoddar](https://togithub.com/rishabhpoddar),
[@&#8203;manovotny](https://togithub.com/manovotny),
[@&#8203;A7med3bdulBaset](https://togithub.com/A7med3bdulBaset),
[@&#8203;huozhi](https://togithub.com/huozhi),
[@&#8203;jridgewell](https://togithub.com/jridgewell),
[@&#8203;joulev](https://togithub.com/joulev),
[@&#8203;SukkaW](https://togithub.com/SukkaW),
[@&#8203;kdy1](https://togithub.com/kdy1),
[@&#8203;feedthejim](https://togithub.com/feedthejim),
[@&#8203;Fredkiss3](https://togithub.com/Fredkiss3),
[@&#8203;styfle](https://togithub.com/styfle),
[@&#8203;MildTomato](https://togithub.com/MildTomato),
[@&#8203;ForsakenHarmony](https://togithub.com/ForsakenHarmony),
[@&#8203;walfly](https://togithub.com/walfly),
[@&#8203;bzhn](https://togithub.com/bzhn),
[@&#8203;shuding](https://togithub.com/shuding),
[@&#8203;boylett](https://togithub.com/boylett),
[@&#8203;Loki899899](https://togithub.com/Loki899899),
[@&#8203;devrsi0n](https://togithub.com/devrsi0n),
[@&#8203;ImBIOS](https://togithub.com/ImBIOS),
[@&#8203;vinaykulk621](https://togithub.com/vinaykulk621),
[@&#8203;ztanner](https://togithub.com/ztanner),
[@&#8203;sdaigo](https://togithub.com/sdaigo),
[@&#8203;hamirmahal](https://togithub.com/hamirmahal),
[@&#8203;blurrah](https://togithub.com/blurrah),
[@&#8203;omarmciver](https://togithub.com/omarmciver), and
[@&#8203;alexBaizeau](https://togithub.com/alexBaizeau) for helping!

###
[`v13.5.3`](https://togithub.com/vercel/next.js/compare/v13.5.2...v13.5.3)

[Compare
Source](https://togithub.com/vercel/next.js/compare/v13.5.2...v13.5.3)

###
[`v13.5.2`](https://togithub.com/vercel/next.js/compare/v13.5.1...v13.5.2)

[Compare
Source](https://togithub.com/vercel/next.js/compare/v13.5.1...v13.5.2)

###
[`v13.5.1`](https://togithub.com/vercel/next.js/compare/v13.5.0...v13.5.1)

[Compare
Source](https://togithub.com/vercel/next.js/compare/v13.5.0...v13.5.1)

###
[`v13.5.0`](https://togithub.com/vercel/next.js/compare/v13.4.19...v13.5.0)

[Compare
Source](https://togithub.com/vercel/next.js/compare/v13.4.19...v13.5.0)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "after 10pm every weekday,before 5am
every weekday,every weekend" in timezone Asia/Tokyo, Automerge - At any
time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/macchiitaka/tasks-app-nextjs).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4zMS41IiwidXBkYXRlZEluVmVyIjoiMzcuMzEuNSIsInRhcmdldEJyYW5jaCI6Im1haW4ifQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>